# Generated by Django 5.2.6 on 2025-09-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('J', 'Job Seeker'), ('R', 'Recruiter')], max_length=20),
        ),
    ]
