# Generated by Django 5.2.5 on 2025-09-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Seen', 'Seen'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='applied', max_length=20),
        ),
    ]
